name: Host tests

on:
  push:
  pull_request:

jobs:
  chassis-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 76076X VEX V5
    steps:
      - uses: actions/checkout@v4

      - name: Build and run host tests
        run: make HOST_BUILD=1
